<h1><?php echo $site; ?> Sample Log</h1>

<a href="">Unit</a>  
<a href="">ect</a>

<table class="sortable tablesorter">
	<thead>
		<tr>
			<th>Lab LF ID</th>
			<th>LF ID</th>
			<th>HF ID</th>
			<th>Bag</th>
			<th>Exc</th>
			<th>Unit</th>
	</thead>
	<tbody>
		<?php $samples = Flots::find(); ?>
		<?php 

			foreach ($samples as $sample) {
				$id = $sample->LabFlot;
				echo "<tr>";
				echo "<th>".$sample->labFlotLink()."</th>";
				echo "<td>".$sample->Flot."</td>";
				echo "<td>".$sample->HFLink()."</td>";
				echo "<td>".$sample->Bag."</td>";
				echo "<td>".$sample->exc()."</td>";
				echo "<td>".$sample->Unit.	"</td>";
				echo "</tr>";
			}
		?>
	</tbody>
</table>
