<h1><?php echo $site; ?> Sample Log</h1>

<table class="sortable tablesorter">
	<thead>
		<tr>
			<th>Lab LF ID</th>
			<th>LF ID</th>
			<th>HF ID</th>
			<th>Bag</th>
			<th>Exc</th>
			<th>Unit</th>
			<th>C14</th>
	</thead>
	<tbody>
		<?php 
			foreach ($samples as $sample) {
				$id = $sample->LabLF;
				echo "<tr>";
				echo "<th>".$sample->labFlotLink()."</th>";
				echo "<td>".$sample->LF."</td>";
				echo "<td>".$sample->HFLink()."</td>";
				echo "<td>".$sample->Bag."</td>";
				echo "<td>".$sample->Exc."</td>";
				echo "<td>".$sample->Unit."</td>";
				echo "<td>".$sample->C14Link()."</td>";
				echo "</tr>";
			}
		?>
	</tbody>
</table>
