<h1>Lab LF ID: <?php echo $LabLF; ?></h1>

<table>
	<thead>
		<tr>
			<th>LF ID</th>
			<th>HF ID</th>
			<th>Locus</th>
			<th>Bag</th>
			<th>Exc</th>
			<th>Unit</th>
	</thead>
	<tbody>
		<?php 
			foreach ($FlotData as $flot) {
				echo "<tr>";
				echo "<td>".$flot->LabLF."</td>";
				echo "<td>".$flot->HFLink()."</td>";
				echo "<td>".$flot->Locus."</td>";
				echo "<td>".$flot->Bag."</td>";
				echo "<td>".$flot->Exc."</td>";
				echo "<td>".$flot->Unit."</td>";
				echo "</tr>";
			}
		?>
	</tbody>
</table>

<div id='tabs'>
	<ul>
		<li><a href="#tab1">Domesticates</a></li>
		<li><a href="#tab2">Families</a></li>
		<li><a href="#tab3">Weeds and Wild</a></li>
		<li><a href="#tab4">Unks &amp; Frags</a></li>
		<li><a href="#tab5">Rachis Remains</a></li>
		<li><a href="#tab6">Other Remains</a></li>
	</ul>

	<div id="tab1" class='tab'>
		<h2>Domesticates</h2>

		<p>linked to wikipedia</p>
		<table>
			<?php meshTableHeader($Doms); ?>
			<?php allMesh($Doms, "Cicer_arietinum"); ?>
			<?php allMesh($Doms, "Coriandrum_sativum"); ?>
			<?php allMesh($Doms, "Ficus_carica"); ?>
			<?php allMesh($Doms, "Hordeum_distichon"); ?>
			<?php allMesh($Doms, "Hordeum_sp"); ?>
			<?php allMesh($Doms, "Hordeum_vulgare"); ?>
			<?php allMesh($Doms, "Indeterminate_Cereal"); ?>
			<?php allMesh($Doms, "Lathyrus_sativa"); ?>
			<?php allMesh($Doms, "Lens_culinaris"); ?>
			<?php allMesh($Doms, "Olea_sp"); ?>
			<?php allMesh($Doms, "Pisum_sativum_ct"); ?>
			<?php allMesh($Doms, "Prunus_sp_cf_cerasifera"); ?>
			<?php allMesh($Doms, "Punica_granatum"); ?>
			<?php allMesh($Doms, "Secale_cereale"); ?>
			<?php allMesh($Doms, "Sorghum_cf_bicolor"); ?>
			<?php allMesh($Doms, "Triticum_aestivum_durum"); ?>
			<?php allMesh($Doms, "Triticum_dicoccum"); ?>
			<?php allMesh($Doms, "Triticum_monococcum"); ?>
			<?php allMesh($Doms, "Triticum_mono_di"); ?>
			<?php allMesh($Doms, "Triticum_sp"); ?>
			<?php allMesh($Doms, "Triticum_spelta"); ?>
			<?php allMesh($Doms, "Vicia_ervilia"); ?>
			<?php allMesh($Doms, "Vicia_faba"); ?>
			<?php allMesh($Doms, "Vicia_sp"); ?>
			<?php allMesh($Doms, "Vitis_vinifera"); ?>

			<?php meshTableFooter($LabLF, "Domesticates"); ?>
		</table>

		<h2>Domesicate Weights</h2>
		<table>
			<?php meshTableHeader($Doms); ?>
			<?php allMesh($Doms, "Olea_sp_shell_frag_wt"); ?>
			<?php allMesh($Doms, "Pisum_sativum_wt"); ?>
			<?php allMesh($Doms, "Olea_sp_wt"); ?>
			<?php meshTableFooter($LabLF, "Domesticates"); ?>
		</table>

		<h2>Other Domesicate Parts</h2>
		<table>
			<?php meshTableHeader($Doms); ?>
			<?php allMesh($Doms, "Vitis_sp_pedicel"); ?>
			<?php allMesh($Doms, "Vitis_vinifera_endocarp"); ?>
			<?php allMesh($Doms, "Vitis_vinifera_endocarp_wt"); ?>
			<?php meshTableFooter($LabLF, "Domesticates"); ?>
		</table>

		<h2>Domesicate Fragments</h2>
		<table>
			<?php meshTableHeader($DomFrags); ?>
			<?php allMesh($DomFrags, "Cereal_frag_CT"); ?>
			<?php allMesh($DomFrags, "Fabaceae_frags"); ?>
			<?php allMesh($DomFrags, "Hordeum_frags"); ?>
			<?php allMesh($DomFrags, "Nutshell_frag"); ?>
			<?php allMesh($DomFrags, "Olea_sp_shell_frag"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_frags"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_frags_wt"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_halves"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_halves_wt"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_whole_distort"); ?>
			<?php allMesh($DomFrags, "Pisum_sativum_whole_distort_wt"); ?>
			<?php allMesh($DomFrags, "Triticum_sp_apex_embryo"); ?>
			<?php allMesh($DomFrags, "Triticum_sp_halves"); ?>
			<?php allMesh($DomFrags, "Vitis_vinifera_frag"); ?>
			<?php meshTableFooter($LabLF, "DomesticateFrags"); ?>
		</table>
	</div>
	
	<div id="tab2" class='tab'>
		<h2>Families</h2>

		<p>linked to wikipedia</p>
		<table>
			<?php meshTableHeader($Fams); ?>
			<?php allMesh($Fams, "Amaranthaceae") ?>
			<?php allMesh($Fams, "Apiaceae") ?>
			<?php allMesh($Fams, "Asteraceae") ?>
			<?php allMesh($Fams, "Boraginaceae_mineralized") ?>
			<?php allMesh($Fams, "Boraginaceae_burnt") ?>
			<?php allMesh($Fams, "Brassicaceae") ?>
			<?php allMesh($Fams, "Caryophyllaceae") ?>
			<?php allMesh($Fams, "Chenopodiaceae") ?>
			<?php allMesh($Fams, "Cyperaceae") ?>
			<?php allMesh($Fams, "Dipsacaceae") ?>
			<?php allMesh($Fams, "Fabaceae") ?>
			<?php allMesh($Fams, "Lamiaceae") ?>
			<?php allMesh($Fams, "Malvaceae") ?>
			<?php allMesh($Fams, "Papaveraceae") ?>
			<?php allMesh($Fams, "Poaceae") ?>
			<?php allMesh($Fams, "Poaceae_Frags") ?>
			<?php allMesh($Fams, "Polygonaceae") ?>
			<?php allMesh($Fams, "Portulaceae") ?>
			<?php allMesh($Fams, "Rubiaceae") ?>
			<?php allMesh($Fams, "Scrophulariaceae") ?>
			<?php allMesh($Fams, "Solanaceae") ?>
			<?php meshTableFooter($LabLF, "FamiliesRemains"); ?>
		</table>
	</div>

	<div id="tab3" class='tab'>
		<h2>Weeds and Wild</h2>

		<p>linked to wikipedia</p>
		<table>
			<?php meshTableHeader($WeedsWilds); ?>
			<?php allMesh($WeedsWilds, "Adonis"); ?>
			<?php allMesh($WeedsWilds, "Agrostemma"); ?>
			<?php allMesh($WeedsWilds, "Aizoon"); ?>
			<?php allMesh($WeedsWilds, "Ajuga"); ?>
			<?php allMesh($WeedsWilds, "Amaranthus"); ?>
			<?php allMesh($WeedsWilds, "Androsace_maxima"); ?>
			<?php allMesh($WeedsWilds, "Anthemis"); ?>
			<?php allMesh($WeedsWilds, "Arnebia"); ?>
			<?php allMesh($WeedsWilds, "Artemisia"); ?>
			<?php allMesh($WeedsWilds, "Asparagus"); ?>
			<?php allMesh($WeedsWilds, "Asphodelus"); ?>
			<?php allMesh($WeedsWilds, "Astragalus"); ?>
			<?php allMesh($WeedsWilds, "Atriplex"); ?>
			<?php allMesh($WeedsWilds, "Avena"); ?>
			<?php allMesh($WeedsWilds, "Bellevalia"); ?>
			<?php allMesh($WeedsWilds, "Brassica"); ?>
			<?php allMesh($WeedsWilds, "Bromus"); ?>
			<?php allMesh($WeedsWilds, "Bupleurum"); ?>
			<?php allMesh($WeedsWilds, "Calendula"); ?>
			<?php allMesh($WeedsWilds, "Camelina"); ?>
			<?php allMesh($WeedsWilds, "Carex"); ?>
			<?php allMesh($WeedsWilds, "Carex_Scirpus"); ?>
			<?php allMesh($WeedsWilds, "Centaurea"); ?>
			<?php allMesh($WeedsWilds, "Cephalaria_syriaca"); ?>
			<?php allMesh($WeedsWilds, "Cerastium"); ?>
			<?php allMesh($WeedsWilds, "cf_Asparagus"); ?>
			<?php allMesh($WeedsWilds, "cf_Berberis"); ?>
			<?php allMesh($WeedsWilds, "cf_Camelina"); ?>
			<?php allMesh($WeedsWilds, "cf_Setaria"); ?>
			<?php allMesh($WeedsWilds, "Chenopodium_album"); ?>
			<?php allMesh($WeedsWilds, "Convolvulus"); ?>
			<?php allMesh($WeedsWilds, "Coronilla"); ?>
			<?php allMesh($WeedsWilds, "Eleocharis"); ?>
			<?php allMesh($WeedsWilds, "Eragrostis"); ?>
			<?php allMesh($WeedsWilds, "Eremo_Agropyron"); ?>
			<?php allMesh($WeedsWilds, "Erodium"); ?>
			<?php allMesh($WeedsWilds, "Erodium_cicutarium_awn"); ?>
			<?php allMesh($WeedsWilds, "Euphorbia"); ?>
			<?php allMesh($WeedsWilds, "Fumaria"); ?>
			<?php allMesh($WeedsWilds, "Galium"); ?>
			<?php allMesh($WeedsWilds, "Glaucium"); ?>
			<?php allMesh($WeedsWilds, "Heliotropium"); ?>
			<?php allMesh($WeedsWilds, "Hippocrepis"); ?>
			<?php allMesh($WeedsWilds, "Hordeum_murinum_boeticum"); ?>
			<?php allMesh($WeedsWilds, "Hyoscyamus"); ?>
			<?php allMesh($WeedsWilds, "Lavatera"); ?>
			<?php allMesh($WeedsWilds, "Lolium"); ?>
			<?php allMesh($WeedsWilds, "Malva"); ?>
			<?php allMesh($WeedsWilds, "Medicago"); ?>
			<?php allMesh($WeedsWilds, "Medicago_type"); ?>
			<?php allMesh($WeedsWilds, "Melilotus_Trifolium"); ?>
			<?php allMesh($WeedsWilds, "Melilotus_Trifolium_punctate"); ?>
			<?php allMesh($WeedsWilds, "Onopordum_Eleusine"); ?>
			<?php allMesh($WeedsWilds, "Ornithogalum"); ?>
			<?php allMesh($WeedsWilds, "Ornithogalum_type"); ?>
			<?php allMesh($WeedsWilds, "Papaver"); ?>
			<?php allMesh($WeedsWilds, "Peganum_harmala"); ?>
			<?php allMesh($WeedsWilds, "Phalaris"); ?>
			<?php allMesh($WeedsWilds, "Phleum"); ?>
			<?php allMesh($WeedsWilds, "Plantago"); ?>
			<?php allMesh($WeedsWilds, "Polygonum"); ?>
			<?php allMesh($WeedsWilds, "Portulaca"); ?>
			<?php allMesh($WeedsWilds, "Rumex"); ?>
			<?php allMesh($WeedsWilds, "Salsola"); ?>
			<?php allMesh($WeedsWilds, "Schinus"); ?>
			<?php allMesh($WeedsWilds, "Scirpus"); ?>
			<?php allMesh($WeedsWilds, "Scorpiurus"); ?>
			<?php allMesh($WeedsWilds, "Silene"); ?>
			<?php allMesh($WeedsWilds, "Stellaria"); ?>
			<?php allMesh($WeedsWilds, "Stipa"); ?>
			<?php allMesh($WeedsWilds, "Suaeda"); ?>
			<?php allMesh($WeedsWilds, "Teucrium"); ?>
			<?php allMesh($WeedsWilds, "Thymelaea"); ?>
			<?php allMesh($WeedsWilds, "Trifolium_repens"); ?>
			<?php allMesh($WeedsWilds, "Trifolium_cf_repens"); ?>
			<?php allMesh($WeedsWilds, "Trigonella"); ?>
			<?php allMesh($WeedsWilds, "Trigonella_astroites"); ?>
			<?php allMesh($WeedsWilds, "Trigonella_coele_syriaca"); ?>
			<?php allMesh($WeedsWilds, "Vaccaria"); ?>
			<?php allMesh($WeedsWilds, "Verbascum"); ?>
			<?php allMesh($WeedsWilds, "Veronica"); ?>
			<?php allMesh($WeedsWilds, "Ziziphora"); ?>
			<?php meshTableFooter($LabLF, "WeedsWilds"); ?>
		</table>
	</div>

	<div id="tab4" class='tab'>
		<h2>Unks &amp; Frags</h2>
		<p>linked to wikipedia</p>
		<table>
			<?php meshTableHeader($Unknowns); ?>
			<?php allMesh($Unknowns, "Clinker"); ?>
			<?php allMesh($Unknowns, "Indeterminate_rachis"); ?>
			<?php allMesh($Unknowns, "Parenchyma_fragment"); ?>
			<?php allMesh($Unknowns, "Rachis_fragment"); ?>
			<?php allMesh($Unknowns, "Unknown_fruit_seed"); ?>
			<?php allMesh($Unknowns, "Unidentifiable_seed_fragment"); ?>
			<?php allMesh($Unknowns, "Unknown_rachis_remains"); ?>
			<?php allMesh($Unknowns, "Unknown_non_Poaceae"); ?>
			<?php meshTableFooter($LabLF, "unknowns"); ?>
		</table>
	</div>

	<div id="tab5" class='tab'>
		<h2>Rachis Remains</h2>

		<p>linked to wikipedia</p>
		<table>
			<?php meshTableHeader($Rachis); ?>
			<?php allMesh($Rachis, "Poaceae_culm"); ?>
			<?php allMesh($Rachis, "Poaceae_root"); ?>
			<?php allMesh($Rachis, "Hordeum_internode"); ?>
			<?php allMesh($Rachis, "Hordeum_rachis"); ?>
			<?php allMesh($Rachis, "Triticum_aestivum_rachis"); ?>
			<?php allMesh($Rachis, "Triticum_aestivum_durum_rachis"); ?>
			<?php allMesh($Rachis, "Triticum_aestivum_durum_rachis_internode"); ?>
			<?php allMesh($Rachis, "Triticum_aestivum_durum_rachis_node"); ?>
			<?php allMesh($Rachis, "Triticum_durum_rachis"); ?>
			<?php allMesh($Rachis, "Triticum_mono_di_rachis"); ?>
			<?php allMesh($Rachis, "Triticum_glume"); ?>
			<?php allMesh($Rachis, "Triticum_internode"); ?>
			<?php allMesh($Rachis, "Triticum_node"); ?>
			<?php allMesh($Rachis, "Triticum_rachis"); ?>
			<?php allMesh($Rachis, "Wild_or_Weed_rachis"); ?>
			<?php meshTableFooter($LabLF, "RachisRemains"); ?>
		</table>
	</div>

	<div id="tab6" class='tab'>
		<h2>Other Remains</h2>

		<table>
			<?php meshTableHeader($Others); ?>
			<?php allMesh($Others, "Bone"); ?>
			<?php allMesh($Others, "Carbonized_insect"); ?>
			<?php allMesh($Others, "Dung"); ?>
			<?php allMesh($Others, "Eggshell"); ?>
			<?php allMesh($Others, "Fish_Scale"); ?>
			<?php allMesh($Others, "Fish_Vertebra"); ?>
			<?php allMesh($Others, "Insect_Pupae"); ?>
			<?php allMesh($Others, "Shell"); ?>
			<?php allMesh($Others, "Shell_Burnt"); ?>
			<?php meshTableFooter($LabLF, "OtherRemains"); ?>
		</table>
	</div>
</div>

<footer>
	<?php echo Phalcon\Tag::linkTo("sample", "Sample Log"); ?>
</footer>