<h1>
	Lab LF ID: <?php echo $FlotData->labFlotLink(); ?>
	<br>
	Edit Unknowns and Fragments
</h1>

<?php echo $this->tag->form('unknowns/update/'); ?>
	<?php echo $this->tag->hiddenField(array("LabLF", "value" => $LabLF)); ?>
	<table>
		<?php meshTableHeader($Unknowns); ?>
		<?php
			meshForm($Unknowns, "Clinker");
			meshForm($Unknowns, "Indeterminate_rachis");
			meshForm($Unknowns, "Parenchyma_fragment");
			meshForm($Unknowns, "Rachis_fragment");
			meshForm($Unknowns, "Unknown_fruit_seed");
			meshForm($Unknowns, "Unidentifiable_seed_fragment");
			meshForm($Unknowns, "Unknown_rachis_remains");
			meshForm($Unknowns, "Unknown_non_Poaceae");
		?>
	</table>
	<?php echo $this->tag->submitButton("Update"); ?>
<?php echo $this->tag->endForm(); ?>
