<h1>
	Lab LF ID: <?php echo $FlotData->labFlotLink(); ?>
	<br>
	Rachis Remains
</h1>

<?php echo $this->tag->form('RachisRemains/update/'); ?>
	<?php echo $this->tag->hiddenField(array("LabLF", "value" => $LabLF)); ?>
	<table>
		<thead>
			<tr>
				<th></th><th colspan='3'>Meshes</th>
			</tr>
			<tr>
				<th></th>
				<?php foreach ($Rachis as $value) {
					echo "<th>".$value->Mesh."</th>";
				} ?>
			</tr>
		</thead>
		<?php
			meshForm($Rachis, "Poaceae_culm");
			meshForm($Rachis, "Poaceae_root");
			meshForm($Rachis, "Hordeum_internode");
			meshForm($Rachis, "Hordeum_rachis");
			meshForm($Rachis, "Triticum_aestivum_rachis");
			meshForm($Rachis, "Triticum_aestivum_durum_rachis");
			meshForm($Rachis, "Triticum_aestivum_durum_rachis_internode");
			meshForm($Rachis, "Triticum_aestivum_durum_rachis_node");
			meshForm($Rachis, "Triticum_durum_rachis");
			meshForm($Rachis, "Triticum_mono_di_rachis");
			meshForm($Rachis, "Triticum_glume");
			meshForm($Rachis, "Triticum_internode");
			meshForm($Rachis, "Triticum_node");
			meshForm($Rachis, "Triticum_rachis");
			meshForm($Rachis, "Wild_or_Weed_rachis");
		?>
	</table>
	<?php echo $this->tag->submitButton("Update"); ?>
<?php echo $this->tag->endForm(); ?>
