<!DOCTYPE html>
<html>
<head>
	<title>Dhiban Data</title>
	<?php 
		$this->assets->addCss('css/style.css');
		$this->assets
			->addJs('js/jquery.min.js')
			->addJs('js/jquery.tablesorter.min.js')
			->addJs('js/jquery.ui.tabs.min.js');
	?>
	<?php $this->assets->outputCss() ?>
	<?php $this->assets->outputJs() ?>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script type="text/javascript">
		$(document).ready(function(){
			$(".sortable").tablesorter(); 
		});
	</script>
</head>

<body>

	<?php echo $this->getContent() ?>

<script>$( "#tabs" ).tabs();</script>

</body>
</html>