<h1>
	Lab LF ID: <?php echo $FlotData->labFlotLink(); ?>
	<br>
	Edit Families
</h1>

<?php echo $this->tag->form('FamiliesRemains/update/'); ?>
	<?php echo $this->tag->hiddenField(array("LabLF", "value" => $LabLF)); ?>
	<table>
		<thead>
			<tr>
				<th></th><th colspan='3'>Meshes</th>
			</tr>
			<tr>
				<th></th>
				<?php foreach ($Fams as $value) {
					echo "<th>".$value->Mesh."</th>";
				} ?>
			</tr>
		</thead>
		<?php
			meshForm($Fams, "Amaranthaceae");
			meshForm($Fams, "Apiaceae");
			meshForm($Fams, "Asteraceae");
			meshForm($Fams, "Boraginaceae_mineralized");
			meshForm($Fams, "Boraginaceae_burnt");
			meshForm($Fams, "Brassicaceae");
			meshForm($Fams, "Caryophyllaceae");
			meshForm($Fams, "Chenopodiaceae");
			meshForm($Fams, "Cyperaceae");
			meshForm($Fams, "Dipsacaceae");
			meshForm($Fams, "Fabaceae");
			meshForm($Fams, "Lamiaceae");
			meshForm($Fams, "Malvaceae");
			meshForm($Fams, "Papaveraceae");
			meshForm($Fams, "Poaceae");
			meshForm($Fams, "Poaceae_Frags");
			meshForm($Fams, "Polygonaceae");
			meshForm($Fams, "Portulaceae");
			meshForm($Fams, "Rubiaceae");
			meshForm($Fams, "Scrophulariaceae");
			meshForm($Fams, "Solanaceae");
		?>
	</table>
	<?php echo $this->tag->submitButton("Update"); ?>
<?php echo $this->tag->endForm(); ?>
